# Generated by Django 5.1.2 on 2024-12-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0002_budget_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='user',
        ),
    ]
