# Generated by Django 5.1.4 on 2024-12-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
