# Generated by Django 5.1.4 on 2025-01-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0009_budgetinitial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transations', to='gestionapp.budget'),
        ),
    ]
