# Generated by Django 5.1.4 on 2025-01-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0011_alter_budget_total_amount_alter_transaction_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
