# Generated by Django 5.1.4 on 2025-01-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0012_alter_budget_total_amount_alter_transaction_montant'),
        ('gestionapp', '0012_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
    ]
